#!/usr/bin/env bash
# images/ ディレクトリをスキャンして data.js を生成する
# 使い方: bash update.sh [画像フォルダのパス]  (省略時は ./images)

set -euo pipefail

IMG_DIR="${1:-images}"
OUT="data.js"
EXTS="jpg jpeg png gif webp avif bmp svg"

if [ ! -d "$IMG_DIR" ]; then
  echo "フォルダが見つかりません: $IMG_DIR"
  echo "  mkdir -p $IMG_DIR  を実行して画像を入れてください。"
  exit 1
fi

# ファイルリストを収集して「更新日時 タブ ファイルパス」形式で取得→新しい順にソート
# macOS (stat -f) と Linux (stat -c) の両方に対応
tmp=$(mktemp)

find "$IMG_DIR" -maxdepth 1 -type f | while IFS= read -r f; do
  basename_f=$(basename "$f")
  ext="${basename_f##*.}"
  ext_lower=$(echo "$ext" | tr '[:upper:]' '[:lower:]')

  skip=1
  for e in $EXTS; do
    [ "$ext_lower" = "$e" ] && skip=0 && break
  done
  [ "$skip" -eq 1 ] && continue

  # 更新日時をエポック秒で取得
  if stat -f '%m' "$f" > /dev/null 2>&1; then
    ts=$(stat -f '%m' "$f")   # macOS
  else
    ts=$(stat -c '%Y' "$f")   # Linux
  fi

  echo "${ts}	${f}"
done | sort -rn > "$tmp"

# data.js を生成
{
  echo "// generated by update.sh on $(date '+%Y-%m-%d %H:%M:%S')"
  echo "const IMAGE_DATA = ["

  while IFS=$'\t' read -r ts path; do
    name=$(basename "$path")
    ms=$((ts * 1000))

    safe_name=$(echo "$name" | sed "s/'/\\\\'/g")
    safe_path=$(echo "$path" | sed "s/'/\\\\'/g")

    printf "  { name: '%s', path: '%s', date: %s },\n" \
      "$safe_name" "$safe_path" "$ms"
  done < "$tmp"

  echo "];"
} > "$OUT"

rm "$tmp"

count=$(grep -c "name:" "$OUT" 2>/dev/null || echo 0)
echo "✔ $OUT を生成しました ($count 枚)"